import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { GUIDES, getGuide } from '@/lib/learn';
import { SITE_URL } from '@/lib/site';

export function generateStaticParams() { return GUIDES.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const guide = getGuide(slug); return { title: guide?.title || 'Learn', description: guide?.summary || 'Luster Studio learning guide.', alternates: { canonical: `${SITE_URL}/learn/${slug}` } }; }

export default async function GuidePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const guide = getGuide(slug); if (!guide) notFound();
  return <main className="min-h-screen bg-canvas text-ink"><div className="mx-auto max-w-4xl px-6 py-12"><Link href="/learn" className="text-[11px] uppercase tracking-[.22em] text-gold/90">← Back to Learn</Link><header className="py-24 md:py-32"><span className="text-[11px] uppercase tracking-[.3em] text-gold/90">Luster Learning · {guide.readingTime}</span><h1 className="mt-5 max-w-3xl font-serif text-6xl tracking-tight md:text-8xl">{guide.title}</h1><p className="mt-8 max-w-2xl text-xl leading-8 text-ink/65">{guide.summary}</p></header>{guide.comingSoon ? <section className="border-y border-ink/10 py-20"><h2 className="font-serif text-4xl">This guide is coming soon.</h2><p className="mt-5 max-w-xl leading-8 text-ink/65">We are preparing a thoughtful, practical guide for this part of the professional workflow.</p><Link href="/learn" className="mt-8 inline-block text-champagne underline underline-offset-4">Explore current guides →</Link></section> : <article>{guide.sections.map((section) => <section key={section.heading} className="border-t border-ink/10 py-12"><h2 className="font-serif text-4xl text-champagne">{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-5 max-w-2xl text-lg leading-8 text-ink/70">{paragraph}</p>)}</section>)}<p className="border-t border-ink/10 py-10 text-sm leading-7 text-ink/55">Technique, preparation, product compatibility, and individual nail conditions affect results. This guide is educational and is not medical advice.</p></article>}<div className="grid gap-8 border-t border-ink/10 py-12 sm:grid-cols-2"><div><p className="text-[11px] uppercase tracking-[.2em] text-gold/90">Related guides</p>{guide.related.map((related) => <Link key={related} href={`/learn/${related}`} className="mt-3 block text-sm text-ink/75 underline underline-offset-4">{getGuide(related)?.title} →</Link>)}</div><div><p className="text-[11px] uppercase tracking-[.2em] text-gold/90">Related products</p><Link href="/shop" className="mt-3 block text-sm text-ink/75 underline underline-offset-4">Explore the Structure System →</Link></div></div></div></main>;
}
